# Generated by Django 5.2 on 2025-08-31 16:00

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=20, unique=True, verbose_name='event ID')),
                ('is_password_protected', models.BooleanField(default=True, verbose_name='password protected')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='password')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=events.models.event_cover_upload_path, verbose_name='cover photo')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('allow_downloads', models.BooleanField(default=True, verbose_name='allow downloads')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(upload_to=events.models.photo_upload_path, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='size in bytes')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='tags')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('video', models.FileField(upload_to=events.models.reel_upload_path, verbose_name='video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=events.models.reel_upload_path, verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in seconds')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='size in bytes')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
            ],
            options={
                'verbose_name': 'reel',
                'verbose_name_plural': 'reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('video', models.FileField(upload_to=events.models.video_upload_path, verbose_name='video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=events.models.video_upload_path, verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in seconds')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='size in bytes')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['created_at'],
            },
        ),
    ]
