# Generated by Django 5.2 on 2025-08-31 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaprocessingjob',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='media.mediafile'),
        ),
        migrations.AddField(
            model_name='storageusage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['event', 'file_type'], name='media_files_event_i_97ce35_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_files_uploade_8ca4da_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['created_at'], name='media_files_created_c209ba_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['storage_provider'], name='media_files_storage_6e5b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['media_file', 'job_type'], name='media_proce_media_f_ff5e35_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['status'], name='media_proce_status_58f7db_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['created_at'], name='media_proce_created_ed2024_idx'),
        ),
    ]
